FROM debian:jessie

MAINTAINER nizq <ni.zhiqiang@gmail.com>

RUN echo "===> Adding dependency..." \
    && apt-get update && apt-get upgrade -y \
    && apt-get install -y libaio1 libcap2-bin libleveldb1 libsnappy1 libseccomp2 jq curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ADD steno* /usr/bin/
ADD libtestimony.so /usr/lib/

VOLUME ["/etc/stenographer", "/data"]
